//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.ServicePortalSubasta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePortalSubasta.IServicePortalSubastas")]
    public interface IServicePortalSubastas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePortalSubastas/listarCompradores", ReplyAction="http://tempuri.org/IServicePortalSubastas/listarCompradoresResponse")]
        Entidades.VCompradores[] listarCompradores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePortalSubastas/listarCompradores", ReplyAction="http://tempuri.org/IServicePortalSubastas/listarCompradoresResponse")]
        System.Threading.Tasks.Task<Entidades.VCompradores[]> listarCompradoresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePortalSubastasChannel : CapaPresentacion.ServicePortalSubasta.IServicePortalSubastas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePortalSubastasClient : System.ServiceModel.ClientBase<CapaPresentacion.ServicePortalSubasta.IServicePortalSubastas>, CapaPresentacion.ServicePortalSubasta.IServicePortalSubastas {
        
        public ServicePortalSubastasClient() {
        }
        
        public ServicePortalSubastasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePortalSubastasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePortalSubastasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePortalSubastasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entidades.VCompradores[] listarCompradores() {
            return base.Channel.listarCompradores();
        }
        
        public System.Threading.Tasks.Task<Entidades.VCompradores[]> listarCompradoresAsync() {
            return base.Channel.listarCompradoresAsync();
        }
    }
}
