//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCompradores
    {
        public int IdComprador { get; set; }
        public string TipoPersona { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string EstadoRepublica { get; set; }
        public string Municipio { get; set; }
        public string Localidad { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Id_Subasta { get; set; }
        public string NombreSubasta { get; set; }
        public string Ruta { get; set; }
    }
}
