//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLoginUsuarios
    {
        public int IdComprador { get; set; }
        public string Nombre { get; set; }
        public string UsuarioAdmin { get; set; }
        public string UsuarioAlterno { get; set; }
        public string Contrasena { get; set; }
        public string EstadoComprador { get; set; }
        public int Id_Subasta { get; set; }
    }
}
