//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOfertas
    {
        public string NombreComprador { get; set; }
        public int Id_Lote { get; set; }
        public string NumeroLote { get; set; }
        public int Id_Comprador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> Id_Subasta { get; set; }
    }
}
