//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante_Pago
    {
        public int Id { get; set; }
        public int Id_Comprador { get; set; }
        public string Ruta { get; set; }
        public int Id_Subasta { get; set; }
        public string NombreSubasta { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Comprador Comprador { get; set; }
    }
}
