//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comprador()
        {
            this.Comprobante_Pago = new HashSet<Comprobante_Pago>();
            this.Login = new HashSet<Login>();
            this.Puja = new HashSet<Puja>();
            this.Puja1 = new HashSet<Puja>();
            this.Seguimiento_Estado_Comprador = new HashSet<Seguimiento_Estado_Comprador>();
            this.Seguimiento_Estado_Comprador1 = new HashSet<Seguimiento_Estado_Comprador>();
        }
    
        public int Id { get; set; }
        public int Id_Tipo { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public string NombreCompleto { get; set; }
        public string RFC { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public int CP { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public bool Activo { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Tipo_Comprador Tipo_Comprador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comprobante_Pago> Comprobante_Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puja> Puja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puja> Puja1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguimiento_Estado_Comprador> Seguimiento_Estado_Comprador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguimiento_Estado_Comprador> Seguimiento_Estado_Comprador1 { get; set; }
    }
}
