//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Puja()
        {
            this.Seguimiento_Puja = new HashSet<Seguimiento_Puja>();
            this.Seguimiento_Puja1 = new HashSet<Seguimiento_Puja>();
        }
    
        public int Id { get; set; }
        public int Id_Comprador { get; set; }
        public int Id_Lote { get; set; }
    
        public virtual Comprador Comprador { get; set; }
        public virtual Comprador Comprador1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguimiento_Puja> Seguimiento_Puja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguimiento_Puja> Seguimiento_Puja1 { get; set; }
    }
}
