//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguimiento_Estado_Comprador
    {
        public int Id { get; set; }
        public int Id_Subasta { get; set; }
        public int Id_Estado_Comprador { get; set; }
        public int Id_Comprador { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Comprador Comprador { get; set; }
        public virtual Comprador Comprador1 { get; set; }
        public virtual Estado_Comprador Estado_Comprador { get; set; }
    }
}
